### ISSUE TITLE
Crash on newDriver on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/oto#126]
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 12 [running]:
github.com/hajimehoshi/oto.newDriver.func2(0xc0000114c8, 0x1000, 0xc000206140, 0xc00005bcc8, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/oto@v0.6.6/driver_darwin.go:144 +0x75
github.com/hajimehoshi/oto.newDriver(0xac44, 0x2, 0x2, 0x2000, 0xc0000b60b8, 0x0, 0x0, 0xb)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/oto@v0.6.6/driver_darwin.go:144 +0x3d5
github.com/hajimehoshi/oto.NewContext(0xac44, 0x2, 0x2, 0x2000, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/oto@v0.6.6/context.go:69 +0xd6
github.com/hajimehoshi/ebiten/v2/audio.(*otoContext).ensureContext.func1()
        /Users/hajimehoshi/ebiten/audio/contextimpl_oto.go:54 +0x75
sync.(*Once).doSlow(0xc0000bb128, 0xc00004deb0)
        /usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/hajimehoshi/ebiten/v2/audio.(*otoContext).ensureContext(0xc0000bb110, 0xc0002a80b8, 0xc000680d80)
        /Users/hajimehoshi/ebiten/audio/contextimpl_oto.go:52 +0x99
github.com/hajimehoshi/ebiten/v2/audio.(*otoPlayer).ensurePlayer(0xc0016e95a0, 0xc00004df48, 0x40086cb)
        /Users/hajimehoshi/ebiten/audio/contextimpl_oto.go:85 +0x32
github.com/hajimehoshi/ebiten/v2/audio.(*otoPlayer).Write(0xc0016e95a0, 0xc001296000, 0x200, 0x200, 0x40425f6, 0x45d9850, 0x45ada51)
        /Users/hajimehoshi/ebiten/audio/contextimpl_oto.go:71 +0x2f
github.com/hajimehoshi/ebiten/v2/audio.(*playerImpl).loop.func3(0xc0002a8060, 0x4652ca0, 0xc0016e95a0, 0xc001601080, 0xc0002a8000)
        /Users/hajimehoshi/ebiten/audio/audio.go:373 +0xa7
created by github.com/hajimehoshi/ebiten/v2/audio.(*playerImpl).loop
        /Users/hajimehoshi/ebiten/audio/audio.go:371 +0x1a6
```

**Comment by hajimehoshi** [comment]
CC @shurcooL

**Comment by dmitshur** [comment]
(@hajimehoshi If you want to CC me, my GitHub username is @dmitshur [as of July 2018](https://twitter.com/dmitshur/status/1021266582834634752).)
