### ISSUE TITLE
Crash with pipewire

### ISSUE THREAD

**Issue by amigan** [ebitengine/oto#243]
Using PipeWire on Linux, I am seeing consistent crashes trying to play another file after already having played one with the same context.

```
goroutine 28 gp=0xc000103500 m=5 mp=0xc000100008 [syscall]:
runtime.cgocall(0x7117b0, 0xc00006ae98)
        /usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00006ae70 sp=0xc00006ae38 pc=0x40748b
github.com/hajimehoshi/oto._Cfunc_snd_pcm_drop(0x77b86805c840)
        _cgo_gotypes.go:150 +0x47 fp=0xc00006ae98 sp=0xc00006ae70 pc=0x4ea567
github.com/hajimehoshi/oto.(*driver).Close.func1(0xc000103500?)
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/driver_linux.go:176 +0x3e fp=0xc00006aed8 sp=0xc00006ae98 pc=0x4eb69e
github.com/hajimehoshi/oto.(*driver).Close(0xc00013a440)
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/driver_linux.go:176 +0x18 fp=0xc00006aef0 sp=0xc00006aed8 pc=0x4eb598
github.com/hajimehoshi/oto.(*driverWriter).Close(0xc000125860)
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/context.go:170 +0xbe fp=0xc00006af40 sp=0xc00006aef0 pc=0x4e9bfe
github.com/hajimehoshi/oto.(*Context).Close(0xc0001365b8)
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/context.go:106 +0x9d fp=0xc00006af80 sp=0xc00006af40 pc=0x4e967d
github.com/hajimehoshi/oto.NewContext.func1()
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/context.go:89 +0x89 fp=0xc00006afe0 sp=0xc00006af80 pc=0x4e9569
runtime.goexit({})
        /usr/lib/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00006afe8 sp=0xc00006afe0 pc=0x46f941
created by github.com/hajimehoshi/oto.NewContext in goroutine 9
        /home/dponte/go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/context.go:84 +0x299
```

gdb backtrace:
```
(gdb) bt
#0  0x00007fffb1074bb0 in ?? () from /usr/lib/alsa-lib/libasound_module_pcm_pipewire.so
#1  0x00007fffb107588c in ?? () from /usr/lib/alsa-lib/libasound_module_pcm_pipewire.so
#2  0x00007ffff7ea19f7 in snd_pcm_ioplug_drop (pcm=0x7fffa405c9a0) at pcm/pcm_ioplug.c:506
#3  0x00007ffff7edf8cf in snd_pcm_drop (pcm=0x7fffa405c9a0) at pcm/pcm.c:1336
#4  0x00000000007117c7 in _cgo_80c47aefa7d0_Cfunc_snd_pcm_drop (v=0xc0002e0e98) at /tmp/go-build/cgo-gcc-prolog:111
#5  0x000000000046f5c4 in runtime.asmcgocall () at /usr/lib/go/src/runtime/asm_amd64.s:918
#6  0x000000c0002ce000 in ?? ()
#7  0x0000000000000000 in ?? ()
```

This (quite expectedly) does not happen with the same code on macOS.

**Comment by amigan** [comment]
Right after posting this, I found a logic error where the context was being reopened. Closed.
